// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ild7CWSnI634c32YkfbvKXxXhvDoOTA',
    appId: '1:871094126702:android:b28a352c7492f344147e7f',
    messagingSenderId: '871094126702',
    projectId: 'easy-1rx-cbc31',
    databaseURL: 'https://easy-1rx-cbc31.firebaseio.com',
    storageBucket: 'easy-1rx-cbc31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqSkSaOcf04cBgFFaB7eFHS2OzBpquETw',
    appId: '1:871094126702:ios:b2ec72949016960f147e7f',
    messagingSenderId: '871094126702',
    projectId: 'easy-1rx-cbc31',
    databaseURL: 'https://easy-1rx-cbc31.firebaseio.com',
    storageBucket: 'easy-1rx-cbc31.appspot.com',
    androidClientId: '871094126702-455ta0qrkbcafmgtmh976tt949k79q0h.apps.googleusercontent.com',
    iosClientId: '871094126702-0tc49r20lor73dd9r74m6jd9ldpt1efn.apps.googleusercontent.com',
    iosBundleId: 'com.ewasfa',
  );
}
